name: Java CI with Gradle

on:
  push:
    branches: [ bedrock ]
  pull_request:
    branches: [ bedrock ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew buildPlugin --no-daemon

    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: build/libs
